### ISSUE TITLE
Alexa pour Synoaudio

### ISSUE THREAD

**Issue by MysterePMS** [nexus79000/synoaudio#3]
Bonjour,
Je viens d'acheté votre plugin, et celui ci ne détecte que ma Freebox Delta.
J'aurais aimé savoir s'il était possible de diffuser l'audio par une de mes "Alexa - Echo Dot" ?
Je suis sous Jeedom.
Merci d'avance

**Comment by nexus79000** [comment]
Bonjour,

Désolé pour la réponse très tardive, mais si Alexa ne propose pas le protocole DLNA AudioStation ne la verra pas.

Ce n'est pas lié au plugin mais directement à AudioStation

Bonne journée
